### ISSUE TITLE
Support read-only journal operations.

### ISSUE THREAD

**Issue by joshuabenuck** [joshuabenuck/denowiki#21]
In order to be a [Federation Friendly Outpost](http://ward.asia.wiki.org/view/federation-friendly-outposts), we need to support read-only journal operations.

This looks to include:
- [x] Generated welcome pages should include a journal.
- [x] Other pages generated server side should include a journal. 86eb30fc40bf589625b6b2dd199ef732600f79ab
- [ ] Support for displaying the journal (on all pages or only those for authenticated servers or do we need to introduce wiki mode?)
- [ ] Support for displaying previous revisions of viewed pages.

**Comment by WardCunningham** [comment]
It is more important to export a well formed journal than to display one locally.

**Comment by joshuabenuck** [comment]
We now serve well formed journal entries for generated pages.

Closing this as the other two items listed (displaying the journal or displaying previous pages) are not currently a priority. What has been implemented is sufficient for now.
