### ISSUE TITLE
wiki.pages registers pages for all registered meta-sites

### ISSUE THREAD

**Issue by joshuabenuck** [joshuabenuck/denowiki#30]
Steps to reproduce:
* Check out `seran-scrape` as a peer to `seran-wiki`
* In `seran-wiki` run `./seran-wiki.sh ../scrape.ts ./meta-sites`
* Go to: `http://seran.localtest.me:8000/index.html?page=federation-scraper`

![image](https://user-images.githubusercontent.com/306384/77553754-736be780-6e72-11ea-9fe0-37766ad1f784.png)

Expected results:
* Only the `scrape.localtest.me` meta-site has a page named `Federation Scraper`.

**Comment by WardCunningham** [comment]
This must be a scope of variable problem when I moved the implementation out of the meta-site that it initially served.

**Comment by joshuabenuck** [comment]
I agree. Perhaps we could add a parameter to the function that is the metaPages object to use when adding the pages? Or we could just return an object with the created pages and callers could `Object.assign` to merge it with their local metaPages?

**Comment by joshuabenuck** [comment]
Fixed by https://github.com/joshuabenuck/seran-wiki/commit/f0153d240ff6420282001967e6b7a72196e21ba0
